# Data Wrangling II - Academic Performance Dataset

This experiment focuses on handling missing values, detecting and treating outliers, and applying data transformations to improve data quality and distribution.

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Name":["abc","lmn","stu","xyz","efg","klm","rst","uvw",np.nan,"def"],
    "Maths":[96,88,np.nan,73,44,88,72,84,93,92],
    "Reading":[77,200,88,np.nan,np.nan,91,78,np.nan,84,93],
    "Writing":[86,np.nan,170,87,69,91,np.nan,88,92,83],
    "Placement":[88,76,91,84,96,84,80,78,np.nan,93],
    "Gender":["Male","Female",np.nan,"Female","Female","Male","Female", "Male", "Male", "Male"],
    "Joining Date":[2018,2019,2022,2018,2017,2023,2016,2020,2020,2019],
    "Region":["Pune","Mumbai","Delhi",np.nan,"Surat","Solapur","Bengaluru","Kolkata",np.nan,"Pune"]
}

df = pd.DataFrame(data)
df

  Name  Maths  Reading  Writing  Placement  Gender  Joining Date     Region
0  abc   96.0     77.0     86.0       88.0    Male          2018       Pune
1  lmn   88.0    200.0      NaN       76.0  Female          2019     Mumbai
2  stu    NaN     88.0    170.0       91.0     NaN          2022      Delhi
3  xyz   73.0      NaN     87.0       84.0  Female          2018        NaN
4  efg   44.0      NaN     69.0       96.0  Female          2017      Surat
5  klm   88.0     91.0     91.0       84.0    Male          2023    Solapur
6  rst   72.0     78.0      NaN       80.0  Female          2016  Bengaluru
7  uvw   84.0      NaN     88.0       78.0    Male          2020    Kolkata
8  NaN   93.0     84.0     92.0        NaN    Male          2020        NaN
9  def   92.0     93.0     83.0       93.0    Male          2019       Pune

## 1. Checking Missing Values and Inconsistencies

Missing values are detected using `isnull()` function.

In [3]:
df.isnull().sum()

Name            1
Maths           1
Reading         3
Writing         2
Placement       1
Gender          1
Joining Date    0
Region          2
dtype: int64

## Handling Missing Values in Numerical Columns

In this step, missing values in numerical columns are handled using **mean imputation**.

- The columns **Maths, Reading, Writing, and Placement** are selected as they contain numerical data.
- The `fillna()` function is used to replace missing values.
- The missing values are replaced with the **mean (average)** of their respective columns.

### Why Mean Imputation?
- It maintains the overall distribution of the data  
- Simple and effective for numerical datasets  
- Prevents data loss compared to dropping rows  

Thus, all missing numerical values are replaced with meaningful values.

In [4]:
num_cols = ["Maths","Reading","Writing","Placement"]

df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

In [5]:
df

,Name,Maths,Reading,Writing,Placement,Gender,Joining Date,Region
0,abc,96.000000,77.000000,86.00,88.000000,Male,2018,Pune
1,lmn,88.000000,200.000000,95.75,76.000000,Female,2019,Mumbai
2,stu,81.111111,88.000000,170.00,91.000000,NaN,2022,Delhi
3,xyz,73.000000,101.571429,87.00,84.000000,Female,2018,NaN
4,efg,44.000000,101.571429,69.00,96.000000,Female,2017,Surat
5,klm,88.000000,91.000000,91.00,84.000000,Male,2023,Solapur
6,rst,72.000000,78.000000,95.75,80.000000,Female,2016,Bengaluru
7,uvw,84.000000,101.571429,88.00,78.000000,Male,2020,Kolkata
8,NaN,93.000000,84.000000,92.00,85.555556,Male,2020,NaN
9,def,92.000000,93.000000,83.00,93.000000,Male,2019,Pune

## Handling Missing Values in Categorical Columns

In this step, missing values in categorical columns are handled using **mode imputation**.

- The columns **Gender** and **Region** are selected as they contain categorical (non-numeric) data.
- A loop is used to process each column individually.
- The `fillna()` function replaces missing values with the **mode** (most frequent value) of that column.

### Why Mode Imputation?
- Suitable for categorical data where mean/median cannot be applied  
- Replaces missing values with the most common category  
- Helps maintain consistency in the dataset  

Thus, missing categorical values are filled with the most frequent category in each column.

In [6]:
cat_cols = ["Gender","Region"]

for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

df

C:\Users\rushi\AppData\Local\Temp\ipykernel_11644\3120366111.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

,Name,Maths,Reading,Writing,Placement,Gender,Joining Date,Region
0,abc,96.000000,77.000000,86.00,88.000000,Male,2018,Pune
1,lmn,88.000000,200.000000,95.75,76.000000,Female,2019,Mumbai
2,stu,81.111111,88.000000,170.00,91.000000,Male,2022,Delhi
3,xyz,73.000000,101.571429,87.00,84.000000,Female,2018,Pune
4,efg,44.000000,101.571429,69.00,96.000000,Female,2017,Surat
5,klm,88.000000,91.000000,91.00,84.000000,Male,2023,Solapur
6,rst,72.000000,78.000000,95.75,80.000000,Female,2016,Bengaluru
7,uvw,84.000000,101.571429,88.00,78.000000,Male,2020,Kolkata
8,NaN,93.000000,84.000000,92.00,85.555556,Male,2020,Pune
9,def,92.000000,93.000000,83.00,93.000000,Male,2019,Pune

## 2. Outlier Detection using IQR Method

In this step, outliers are detected using the **Interquartile Range (IQR) method**.

### Steps Performed:

- **Q1 (First Quartile)**: Represents the 25th percentile of the data  
- **Q3 (Third Quartile)**: Represents the 75th percentile of the data  
- **IQR (Interquartile Range)**: Calculated as  
  IQR = Q3 − Q1  
  It represents the range of the middle 50% of the data  

### Outlier Detection Rule:

- Lower Bound = Q1 − 1.5 × IQR  
- Upper Bound = Q3 + 1.5 × IQR  

Any value:
- Less than the lower bound, or  
- Greater than the upper bound  

is considered an **outlier**.

### Output:

- The result is a boolean DataFrame:
  - **True** → indicates an outlier  
  - **False** → indicates a normal value  

This method helps in identifying extreme values that may affect data analysis.

In [7]:
Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1

outliers = ((df[num_cols] < (Q1 - 1.5 * IQR)) | (df[num_cols] > (Q3 + 1.5 * IQR)))

outliers

   Maths  Reading  Writing  Placement
0  False    False    False      False
1  False     True    False      False
2  False    False     True      False
3  False    False    False      False
4   True    False     True      False
5  False    False    False      False
6  False    False    False      False
7  False    False    False      False
8  False    False    False      False
9  False    False    False      False

In [8]:
df

,Name,Maths,Reading,Writing,Placement,Gender,Joining Date,Region
0,abc,96.000000,77.000000,86.00,88.000000,Male,2018,Pune
1,lmn,88.000000,200.000000,95.75,76.000000,Female,2019,Mumbai
2,stu,81.111111,88.000000,170.00,91.000000,Male,2022,Delhi
3,xyz,73.000000,101.571429,87.00,84.000000,Female,2018,Pune
4,efg,44.000000,101.571429,69.00,96.000000,Female,2017,Surat
5,klm,88.000000,91.000000,91.00,84.000000,Male,2023,Solapur
6,rst,72.000000,78.000000,95.75,80.000000,Female,2016,Bengaluru
7,uvw,84.000000,101.571429,88.00,78.000000,Male,2020,Kolkata
8,NaN,93.000000,84.000000,92.00,85.555556,Male,2020,Pune
9,def,92.000000,93.000000,83.00,93.000000,Male,2019,Pune

## Outlier Treatment using Capping (Clipping)

After detecting outliers, they are handled using the **capping method** with the help of the `clip()` function.

### Steps Performed:

- The **lower bound** is calculated as:  
  Lower Bound = Q1 − 1.5 × IQR  

- The **upper bound** is calculated as:  
  Upper Bound = Q3 + 1.5 × IQR  

### Outlier Treatment:

- Values below the lower bound are replaced with the lower bound  
- Values above the upper bound are replaced with the upper bound  
- Values within the range remain unchanged  

### Why Clipping?

- Prevents extreme values from affecting analysis  
- Retains all data points (no data loss)  
- Maintains consistency in the dataset  

The `clip()` function applies these bounds column-wise (using `axis=1`), ensuring each numerical column is treated independently.

In [9]:
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df[num_cols] = df[num_cols].clip(lower=lower, upper=upper, axis=1)

df

,Name,Maths,Reading,Writing,Placement,Gender,Joining Date,Region
0,abc,96.000000,77.000000,86.00000,88.000000,Male,2018,Pune
1,lmn,88.000000,126.428571,95.75000,76.000000,Female,2019,Mumbai
2,stu,81.111111,88.000000,107.65625,91.000000,Male,2022,Delhi
3,xyz,73.000000,101.571429,87.00000,84.000000,Female,2018,Pune
4,efg,51.069444,101.571429,73.40625,96.000000,Female,2017,Surat
5,klm,88.000000,91.000000,91.00000,84.000000,Male,2023,Solapur
6,rst,72.000000,78.000000,95.75000,80.000000,Female,2016,Bengaluru
7,uvw,84.000000,101.571429,88.00000,78.000000,Male,2020,Kolkata
8,NaN,93.000000,84.000000,92.00000,85.555556,Male,2020,Pune
9,def,92.000000,93.000000,83.00000,93.000000,Male,2019,Pune

## 3. Data Transformation

Data transformation is applied to improve the distribution of data.  
Here, log transformation is used to reduce skewness and make the data more normally distributed.

In [10]:
df["Maths_log"] = np.log(df["Maths"])
df

,Name,Maths,Reading,Writing,Placement,Gender,Joining Date,Region,Maths_log
0,abc,96.000000,77.000000,86.00000,88.000000,Male,2018,Pune,4.564348
1,lmn,88.000000,126.428571,95.75000,76.000000,Female,2019,Mumbai,4.477337
2,stu,81.111111,88.000000,107.65625,91.000000,Male,2022,Delhi,4.395820
3,xyz,73.000000,101.571429,87.00000,84.000000,Female,2018,Pune,4.290459
4,efg,51.069444,101.571429,73.40625,96.000000,Female,2017,Surat,3.933186
5,klm,88.000000,91.000000,91.00000,84.000000,Male,2023,Solapur,4.477337
6,rst,72.000000,78.000000,95.75000,80.000000,Female,2016,Bengaluru,4.276666
7,uvw,84.000000,101.571429,88.00000,78.000000,Male,2020,Kolkata,4.430817
8,NaN,93.000000,84.000000,92.00000,85.555556,Male,2020,Pune,4.532599
9,def,92.000000,93.000000,83.00000,93.000000,Male,2019,Pune,4.521789

### Reason for Transformation

- Log transformation reduces skewness in the data  
- Helps in converting non-linear relationships into linear ones  
- Improves performance of machine learning models