# Assignment 3

## Problem Statement

Implement Logistic Regression using Python to perform classification on the Social_Network_Ads.csv dataset.

Compute the following evaluation metrics:
- True Positive (TP)
- True Negative (TN)
- False Positive (FP)
- False Negative (FN)
- Accuracy
- Error Rate
- Precision
- Recall

# Import Libraries

We import the required libraries for data manipulation and machine learning:

- pandas → for handling dataset
- numpy → for numerical operations
- matplotlib → for visualization (optional)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load Dataset

The dataset is loaded using pandas read_csv() function.

- The dataset file should be present inside the 'datasets' folder.
- head() is used to display the first 5 rows.

In [2]:
df = pd.read_csv("Datasets/Social_Network_Ads.csv")
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

# Data Preprocessing

Steps performed:

1. Remove 'User ID' column as it is not useful for prediction.
2. Convert categorical column 'Gender' into numeric using one-hot encoding.

pd.get_dummies() is used to convert categorical values into binary columns.

# Define Features and Target

- X → Independent variables (Age, Salary, Gender)
- y → Dependent variable (Purchased)

The model learns from X to predict y.

In [3]:
x = df.drop(['User ID', 'Purchased', 'Gender'], axis=1)
x

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [4]:

y = df['Purchased']
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

# Train-Test Split

The dataset is divided into:

- Training data (80%) → used to train model
- Testing data (20%) → used to evaluate model

random_state ensures reproducibility.

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

# Feature Scaling

Feature scaling standardizes the data so that all features contribute equally.

StandardScaler transforms data such that:
- Mean = 0
- Standard deviation = 1

This improves performance of Logistic Regression.

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train Logistic Regression Model

Logistic Regression is used for binary classification.

- fit() trains the model on training data
- It learns relationship between features and target

In [7]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

In [8]:

y_test = classifier.predict(X_test)

In [9]:

y_train

3      0
18     1
202    1
250    0
274    1
      ..
71     0
106    0
270    0
348    0
102    0
Name: Purchased, Length: 320, dtype: int64

In [10]:
y_test

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0])

# Make Predictions

The trained model is used to predict values on test data using predict() function.

In [11]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0])

# Confusion Matrix

Confusion matrix shows prediction results:

              Predicted
              1     0
                
Actual 1    -------        TP --------  FN

Actual 0     --------       FP --------    TN

Where:
- TP → Correct positive prediction
- TN → Correct negative prediction
- FP → Incorrect positive prediction
- FN → Incorrect negative prediction

In [12]:
from sklearn.metrics import confusion_matrix,classification_report, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[59  0]
 [ 0 21]]

In [13]:

score = accuracy_score(y_test, y_pred)
score

1.0

In [14]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        59
           1       1.00      1.00      1.00        21

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80

In [15]:
print('True Positive:', cm[0][0])
print('True Negative:', cm[1][1])
print('False Positive:', cm[0][1])
print('False Negative:', cm[1][0])
print('Accuracy:', score)
print('Error Rate:', 1-score)
precision = cm[0][0]/(cm[0][0]+cm[0][1])
print('Precision:', precision)

True Positive: 59
True Negative: 21
False Positive: 0
False Negative: 0
Accuracy: 1.0
Error Rate: 0.0
Precision: 1.0

# Evaluation Metrics

Formulas:

- Accuracy = (TP + TN) / TP + TN + FP + FN
- Error Rate = 1 - Accuracy
- Precision = TP / (TP + FP)
- Recall = TP / (TP + FN)

These metrics evaluate model performance.